name: Lint & Test & Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Check #1: Lint
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0

      # Check #2: Test
      - name: Test
        run: make tests

      # Check #3: Build
      - name: Build Server
        run: make build
